version: '3.8'
services:
  front:
    build: ./public
    volumes:
      - ./public:/src
    ports:
      - "5173:5173"
    command: npm run dev 


  api:
    build: ./server
    volumes:
      - ./server:/index.js
    ports:
      - "5000:5000"  
    command: npm run start  